# Generated by Django 3.1.5 on 2021-01-31 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('kundennummer', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nachname', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.CharField(max_length=50)),
                ('rahmennummer', models.CharField(max_length=30)),
                ('kundennummer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_profile.customer')),
            ],
            options={
                'verbose_name': 'Bike',
                'verbose_name_plural': 'Bikes',
            },
        ),
    ]
