# Generated by Django 3.1.5 on 2021-01-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='insurance',
            field=models.CharField(choices=[('no', 'None'), ('as', 'Assona'), ('bu', 'Businessbike'), ('bl', 'Bikeleasing Service'), ('en', 'ENRA'), ('eu', 'Eurorad')], default='no', help_text='Versicherungsunternehmen', max_length=2),
        ),
    ]
