# Generated by Django 3.1.5 on 2021-02-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_profile', '0002_bike_insurance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='insurance',
            new_name='insurance_company',
        ),
    ]
