# Generated by Django 3.1.5 on 2021-02-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_profile', '0003_auto_20210203_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='insurance_company',
        ),
        migrations.AddField(
            model_name='bike',
            name='versicherungsunternehmen',
            field=models.CharField(choices=[('no', 'None'), ('as', 'Assona'), ('bu', 'Businessbike'), ('bl', 'Bikeleasing Service'), ('en', 'ENRA'), ('eu', 'Eurorad')], default='no', max_length=2),
        ),
    ]
