# Generated by Django 3.1.4 on 2021-07-22 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={'verbose_name': 'Fahrrad', 'verbose_name_plural': 'Fahrräder'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Kunde', 'verbose_name_plural': 'Kunden'},
        ),
    ]
