# Generated by Django 3.1.4 on 2020-12-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssonaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kundennummer', models.IntegerField()),
                ('nachname', models.CharField(max_length=30)),
                ('fahrzeug', models.CharField(max_length=50)),
                ('rahmennummer', models.CharField(max_length=30)),
                ('vertragsnummer', models.CharField(max_length=10)),
                ('beginn', models.DateField()),
            ],
        ),
    ]
