# Generated by Django 3.1.5 on 2021-02-14 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210214_1718'),
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assonainfo',
            name='bike',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='customers.bike', to_field='rahmennummer'),
            preserve_default=False,
        ),
    ]
