# Generated by Django 3.1.4 on 2021-02-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='euroradinfo',
            name='versicherungskarte',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
