# Generated by Django 3.1.5 on 2021-01-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeleasingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kundennummer', models.IntegerField()),
                ('nachname', models.CharField(max_length=30)),
                ('fahrzeug', models.CharField(max_length=50)),
                ('rahmennummer', models.CharField(max_length=30)),
                ('nutzer_id', models.CharField(max_length=20)),
                ('paket', models.CharField(choices=[('P', 'Premium'), ('P+', 'Premium Plus')], max_length=20)),
                ('inspektion', models.BooleanField()),
                ('leasingbank', models.CharField(choices=[('ALS', 'ALS Leasing GmbH'), ('Hofmann', 'Hofmann Leasing GmbH'), ('Digital Mobility', 'Digital Mobility Leasing GmbH')], max_length=20)),
                ('beginn', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessbikeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kundennummer', models.IntegerField()),
                ('nachname', models.CharField(max_length=30)),
                ('fahrzeug', models.CharField(max_length=50)),
                ('rahmennummer', models.CharField(max_length=30)),
                ('beginn', models.DateField()),
                ('ende', models.DateField()),
                ('policenummer', models.CharField(max_length=30)),
                ('paket', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EnraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kundennummer', models.IntegerField()),
                ('nachname', models.CharField(max_length=30)),
                ('fahrzeug', models.CharField(max_length=50)),
                ('rahmennummer', models.CharField(max_length=30)),
                ('beginnn', models.DateField()),
                ('policenummer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EuroradInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kundennummer', models.IntegerField()),
                ('nachname', models.CharField(max_length=30)),
                ('fahrzeug', models.CharField(max_length=50)),
                ('rahmennummer', models.CharField(max_length=30)),
                ('beginn', models.DateField()),
                ('vertragsnummer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(choices=[('ASSONA', 'Assona'), ('BIKELEASING SERVICE', 'BikeleasingService'), ('BUSINESSBIKE', 'Businessbike'), ('ENRA', 'ENRA'), ('EURORAD', 'Eurorad')], default='ASSONA', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='assonainfo',
            name='fahrzeug',
        ),
        migrations.RemoveField(
            model_name='assonainfo',
            name='kundennummer',
        ),
        migrations.RemoveField(
            model_name='assonainfo',
            name='nachname',
        ),
        migrations.RemoveField(
            model_name='assonainfo',
            name='rahmennummer',
        ),
    ]
