# Generated by Django 3.1.5 on 2021-02-15 20:55

import apps.insurance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_euroradinfo_versicherungskarte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assonainfo',
            name='versicherungskarte',
            field=models.FileField(blank=True, upload_to=apps.insurance.models.set_upload_path),
        ),
        migrations.AlterField(
            model_name='bikeleasinginfo',
            name='versicherungskarte',
            field=models.FileField(blank=True, upload_to=apps.insurance.models.set_upload_path),
        ),
        migrations.AlterField(
            model_name='businessbikeinfo',
            name='versicherungskarte',
            field=models.FileField(blank=True, upload_to=apps.insurance.models.set_upload_path),
        ),
        migrations.AlterField(
            model_name='enrainfo',
            name='versicherungskarte',
            field=models.FileField(blank=True, upload_to=apps.insurance.models.set_upload_path),
        ),
        migrations.AlterField(
            model_name='euroradinfo',
            name='versicherungskarte',
            field=models.FileField(blank=True, upload_to=apps.insurance.models.set_upload_path),
        ),
    ]
