# Generated by Django 3.1.5 on 2021-02-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_assonainfo_bike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assonainfo',
            name='bike',
            field=models.CharField(max_length=30),
        ),
    ]
