# Generated by Django 3.1.5 on 2021-02-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_auto_20210202_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='assonainfo',
            name='karte',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bikeleasinginfo',
            name='guthaben_erschopft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikeleasinginfo',
            name='karte',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='businessbikeinfo',
            name='karte',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='enrainfo',
            name='karte',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='insurancecompanies',
            name='company_name',
            field=models.CharField(choices=[('no', 'None'), ('as', 'Assona'), ('bs', 'Bikeleasing Service'), ('bu', 'Businessbike'), ('en', 'ENRA'), ('eu', 'Eurorad')], default='no', max_length=2),
        ),
    ]
