# Generated by Django 3.1.5 on 2021-03-08 20:53

import apps.insurance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_auto_20210215_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assonainfo',
            name='versicherungskarte',
            field=models.FileField(blank=True, upload_to=apps.insurance.models.set_path_and_rename),
        ),
        migrations.AlterField(
            model_name='bikeleasinginfo',
            name='versicherungskarte',
            field=models.FileField(blank=True, upload_to=apps.insurance.models.set_path_and_rename),
        ),
        migrations.AlterField(
            model_name='businessbikeinfo',
            name='versicherungskarte',
            field=models.FileField(blank=True, upload_to=apps.insurance.models.set_path_and_rename),
        ),
        migrations.AlterField(
            model_name='enrainfo',
            name='versicherungskarte',
            field=models.FileField(blank=True, upload_to=apps.insurance.models.set_path_and_rename),
        ),
        migrations.AlterField(
            model_name='euroradinfo',
            name='versicherungskarte',
            field=models.FileField(blank=True, upload_to=apps.insurance.models.set_path_and_rename),
        ),
    ]
