# Generated by Django 3.1.5 on 2021-02-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_auto_20210203_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assonainfo',
            old_name='karte',
            new_name='versicherungskarte',
        ),
        migrations.RenameField(
            model_name='bikeleasinginfo',
            old_name='karte',
            new_name='versicherungskarte',
        ),
        migrations.RenameField(
            model_name='businessbikeinfo',
            old_name='karte',
            new_name='versicherungskarte',
        ),
        migrations.RenameField(
            model_name='enrainfo',
            old_name='karte',
            new_name='versicherungskarte',
        ),
    ]
