# Generated by Django 3.1.5 on 2021-02-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_auto_20210203_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikeleasinginfo',
            name='guthaben_erschopft',
        ),
        migrations.AddField(
            model_name='businessbikeinfo',
            name='verschleiss_guthaben',
            field=models.BooleanField(default=False),
        ),
    ]
