# Generated by Django 3.1.5 on 2021-02-14 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210214_1718'),
        ('insurance', '0005_auto_20210214_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assonainfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='assonainfo',
            name='rahmennummer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='customers.bike', to_field='rahmennummer'),
        ),
    ]
