# Generated by Django 3.1.5 on 2021-02-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_auto_20210203_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrainfo',
            old_name='beginnn',
            new_name='beginn',
        ),
        migrations.AlterField(
            model_name='insurancecompanies',
            name='company_name',
            field=models.CharField(choices=[('no', 'None'), ('as', 'Assona'), ('bl', 'Bikeleasing Service'), ('bu', 'Businessbike'), ('en', 'ENRA'), ('eu', 'Eurorad')], default='no', max_length=2),
        ),
    ]
