# Generated by Django 3.1.5 on 2021-06-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_schadensmeldung_schadensmeldungupdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchadensmeldungUpdate',
            new_name='SchadensmeldungStatus',
        ),
        migrations.AlterField(
            model_name='schadensmeldung',
            name='reparatur_datum',
            field=models.DateField(null=True),
        ),
    ]
