# Generated by Django 3.1.5 on 2021-06-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_auto_20210630_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schadensmeldung',
            name='reparatur_datum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
