# Generated by Django 3.1.4 on 2021-07-08 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('insurance', '0008_auto_20210630_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schadensmeldung',
            old_name='vorgangsnummer',
            new_name='auftragsnr',
        ),
        migrations.RemoveField(
            model_name='schadensmeldung',
            name='kundenname',
        ),
        migrations.RemoveField(
            model_name='schadensmeldung',
            name='kundennummer',
        ),
        migrations.AddField(
            model_name='schadensmeldung',
            name='kunde',
            field=models.ForeignKey(default=10000, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schadensmeldung',
            name='rechnungsnr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='schadensmeldung',
            name='unternehmen',
            field=models.CharField(choices=[('as', 'Assona')], max_length=3),
        ),
    ]
