# Generated by Django 3.1.4 on 2021-07-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_auto_20210708_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schadensmeldung',
            name='unternehmen',
            field=models.CharField(choices=[('as', 'Assona'), ('bu', 'Businessbike'), ('jo', 'JobRad')], max_length=3),
        ),
    ]
