# Generated by Django 3.1.4 on 2021-07-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0013_auto_20210716_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecompanies',
            name='company_name',
            field=models.CharField(choices=[('no', 'None'), ('as', 'Assona'), ('bl', 'Bikeleasing Service'), ('bu', 'Businessbike'), ('en', 'ENRA'), ('eu', 'Eurorad'), ('we', 'Wertgarantie'), ('so', 'Sonstige')], default='no', max_length=2),
        ),
    ]
