# Generated by Django 3.1.5 on 2021-07-16 20:52

import apps.insurance.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0013_auto_20210716_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchadensmeldungFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('beschreibung', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to=apps.insurance.models.set_schadenfile_path_and_name)),
                ('anmerkung', models.TextField(blank=True)),
                ('schadensmeldung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.schadensmeldung')),
            ],
        ),
    ]
