# Generated by Django 3.1.5 on 2021-07-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0014_schadensmeldungfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schadensmeldung',
            name='unternehmen',
            field=models.CharField(choices=[('as', 'Assona'), ('bi', 'Bikeleasing-Service'), ('bu', 'Businessbike'), ('en', 'ENRA'), ('jo', 'JobRad'), ('le', 'Lease-a-Bike'), ('me', 'Mein-Dienstrad'), ('we', 'Wertgarantie')], max_length=3),
        ),
    ]
