# Generated by Django 3.1.4 on 2021-07-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0014_auto_20210719_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schadensmeldung',
            name='unternehmen',
            field=models.CharField(choices=[('as', 'Assona'), ('bi', 'Bikeleasing-Service'), ('bu', 'Businessbike'), ('en', 'ENRA'), ('jo', 'JobRad'), ('le', 'Lease-a-Bike'), ('we', 'Wertgarantie'), ('so', 'Sonstige')], max_length=3),
        ),
    ]
