# Generated by Django 3.1.4 on 2021-07-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0015_auto_20210719_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecompanies',
            name='company_name',
            field=models.CharField(choices=[('no', 'None'), ('as', 'Assona'), ('bl', 'Bikeleasing Service'), ('bu', 'Businessbike'), ('en', 'ENRA'), ('eu', 'Eurorad')], default='no', max_length=2),
        ),
        migrations.AlterField(
            model_name='schadensmeldung',
            name='unternehmen',
            field=models.CharField(choices=[('as', 'Assona'), ('bi', 'Bikeleasing-Service'), ('bu', 'Businessbike'), ('en', 'ENRA'), ('jo', 'JobRad'), ('le', 'Lease-a-Bike'), ('me', 'Mein-Dienstrad'), ('we', 'Wertgarantie'), ('so', 'Sonstige')], max_length=3),
        ),
    ]
