# Generated by Django 3.1.4 on 2021-07-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0016_auto_20210722_0814'),
        ('insurance', '0015_auto_20210716_2325'),
    ]

    operations = [
    ]
