# Generated by Django 3.1.4 on 2021-07-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0017_merge_20210722_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schadensmeldungstatus',
            name='status',
            field=models.CharField(choices=[('kv', 'KV eingereicht'), ('kvf', 'KV freigegeben'), ('re', 'Rechnung eingereicht'), ('be', 'Bezahlt'), ('abr', 'Abzurechnen'), ('ab', 'Abgelehnt')], max_length=3),
        ),
    ]
