# Generated by Django 3.1.4 on 2021-10-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_schadensmeldung_schadensmeldungstatus'),
        ('insurance', '0020_auto_20210922_1350'),
    ]

    operations = [
    ]
