# Generated by Django 3.1.5 on 2021-03-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('bearbeitung', 'In Bearbeitung'), ('erledigt', 'Erledigt')], default='offen', max_length=15)),
                ('kundenname', models.CharField(max_length=30)),
                ('telefonnr', models.CharField(max_length=20)),
                ('anmerkungen', models.TextField()),
            ],
        ),
    ]
