# Generated by Django 3.1.5 on 2021-03-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecontact',
            name='abteilung',
            field=models.CharField(choices=[('werkstatt', 'Werkstatt'), ('verkauf', 'Verkauf'), ('buero', 'Büro')], default='werkstatt', max_length=15),
            preserve_default=False,
        ),
    ]
