# Generated by Django 3.1.5 on 2021-03-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_phonecontact_abteilung'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecontact',
            name='gesprochen_mit',
            field=models.CharField(default=59, max_length=32),
            preserve_default=False,
        ),
    ]
