# Generated by Django 3.1.5 on 2021-03-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_phonecontact_gesprochen_mit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecontact',
            name='gesprochen_mit',
            field=models.CharField(choices=[(5, 'B. Thürnau'), (12, 'T. Beskowski'), (13, 'J. Wienkötter'), (14, 'T. Koesling'), (20, 'K. Gorlov'), (21, 'F. Hinderks'), (23, 'A. Marutschke'), (28, 'M. Wilholt'), (30, 'T. Schweter'), (34, 'F. Wegener'), (36, 'S. Grotepaß'), (38, 'R. Weiler'), (52, 'S. Zietemann'), (56, 'J. Wiholt'), (58, 'V. Koncur'), (59, 'R. Daly'), (60, 'Hohendorf'), (61, 'E. Betke'), (63, 'C. Siebert'), (64, 'L. Kurowski'), (65, 'S. Bachmann'), (68, 'L. Duhme'), (70, 'F. Nolte'), (72, 'R. Korpilla'), (73, 'F. Stresemann')], max_length=32),
        ),
    ]
