# Generated by Django 3.1.4 on 2021-07-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20210716_2252'),
        ('contact', '0008_auto_20210719_0929'),
    ]

    operations = [
    ]
