# Generated by Django 3.1.5 on 2021-02-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklaticket',
            name='hersteller',
            field=models.CharField(choices=[('absolut', 'Absolut'), ('abus', 'Abus'), ('alpina', 'Alpina'), ('asista', 'Asista'), ('bergamont', 'Bergamont'), ('bosch', 'Bosch'), ('cosmic', 'Cosmic'), ('cube', 'Cube'), ('ergotec', 'Ergotec'), ('grofa', 'Grofa'), ('hamax', 'Hamax'), ('hartje', 'Hartje'), ('magura', 'Magura'), ('mcg', 'MCG'), ('new wave', 'New Wave'), ('oneal', "O'neal"), ('ortlieb', 'Ortlieb'), ('lange', 'Paul Lange'), ('puky', 'Puky'), ('rm', 'R&M'), ('roeckl', 'Roeckl'), ('rti', 'RIT'), ('sks', 'SKS'), ('sonstige', 'Sonstige'), ('sqlab', 'SQ-Lab'), ('sram', 'SRAM DSD'), ('supernova', 'Supernova'), ('trek', 'Trek'), ('trelock', 'Trelock'), ('vaude', 'Vaude'), ('wiener', 'Wiender'), ('zeg', 'ZEG')], max_length=30),
        ),
    ]
