# Generated by Django 3.1.5 on 2021-02-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0002_auto_20210217_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reklaticket',
            options={'permissions': (('can_create', 'Create Rekla Tickets'), ('can_edit', 'Edit Rekla Tickets'), ('can_fuck', 'Can fuck hookers and do cocaine'))},
        ),
    ]
