# Generated by Django 3.1.5 on 2021-02-17 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0003_auto_20210217_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reklaticket',
            options={'permissions': (('can_update_status', 'Can update ReklaTicket status'),)},
        ),
        migrations.CreateModel(
            name='ReklaStatusUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('gemeldet', 'Beim Hersteller gemeldet'), ('eingeschickt', 'Zum Hersteller eingeschickt'), ('wartet', 'Wartet auf bearbeitung beim Hersteller'), ('eingetroffen', 'Ersatz eingetroffen'), ('montage', 'Wartet auf Montage'), ('abholbereit', 'Abholbereit'), ('abgelehnt', 'vom Hersteller abgelehnt'), ('erledigt', 'Erledit')], max_length=20)),
                ('anmerkung', models.TextField()),
                ('rekla_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warranty.reklaticket')),
            ],
        ),
        migrations.CreateModel(
            name='ReklaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('beschreibung', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='')),
                ('anmerkung', models.TextField()),
                ('rekla_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warranty.reklaticket')),
            ],
        ),
    ]
