# Generated by Django 3.1.5 on 2021-02-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0004_auto_20210217_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reklaticket',
            old_name='date_created',
            new_name='angenommen',
        ),
        migrations.AddField(
            model_name='reklaticket',
            name='created',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reklaticket',
            name='update',
            field=models.DateField(default='2021-02-17'),
            preserve_default=False,
        ),
    ]
