# Generated by Django 3.1.5 on 2021-02-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0006_remove_reklaticket_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reklaticket',
            old_name='update',
            new_name='updated',
        ),
    ]
