# Generated by Django 3.1.5 on 2021-02-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0008_auto_20210217_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reklastatusupdate',
            old_name='rekla_ticket_id',
            new_name='rekla_ticket',
        ),
    ]
