# Generated by Django 3.1.4 on 2021-03-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0010_auto_20210218_0958'),
        ('warranty', '0011_auto_20210308_2153'),
    ]

    operations = [
    ]
