# Generated by Django 3.1.5 on 2021-03-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0012_merge_20210309_0919'),
        ('warranty', '0012_auto_20210314_2026'),
    ]

    operations = [
    ]
