# Generated by Django 3.1.4 on 2021-03-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0013_merge_20210315_1119'),
        ('warranty', '0014_auto_20210329_2137'),
    ]

    operations = [
    ]
