# Generated by Django 3.1.4 on 2021-04-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0016_auto_20210421_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reklaticket',
            name='abteilung',
        ),
        migrations.AlterField(
            model_name='reklaticket',
            name='sachbearbeiter',
            field=models.CharField(choices=[('12', 'Beskowski'), ('34', 'Wegener'), ('59', 'Daly'), ('61', 'Betke'), ('65', 'Bachmann'), ('68', 'Duhme'), ('70', 'Nolte'), ('72', 'Korpilla')], max_length=2),
        ),
    ]
