# Generated by Django 3.1.4 on 2021-07-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0018_auto_20210722_0845'),
        ('warranty', '0018_auto_20210722_0814'),
    ]

    operations = [
    ]
